kind: pipeline
type: docker
name: default

steps:
- name: build and push
  image: gcr.io/kaniko-project/executor:v1.9.0-debug
  pull: if-not-exists
  commands:
    - |
      echo "$PLUGIN_SERVICE_ACCOUNT_JSON" > "$GOOGLE_APPLICATION_CREDENTIALS"
      /kaniko/executor --context=/drone/src --destination=$PLUGIN_IMAGE
- name: deploy to cloud run
  image: docker.io/kameshsampath/drone-gcloud-run