namespace: harness-delegate-ng
resources:
  - "harness-delegate.yml"
configMapGenerator:
  - name: harness-tutorial-config
    envs:
      - .env
secretGenerator:
  - name: harness-tutorial-credentials
    files:
      - "harness-tutorial-sa-key.json"
patchesStrategicMerge:
  - patch.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: local-kind
  path: envFrom.yaml